AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Chessfinder - application for finding chessgame having only partial information about the game.

Resources:
  Roles:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/role.yaml

  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/db.yaml

  SQS:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/queue.yaml

  Async:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/async.yaml
      Parameters:
        ChessfinderLambdaRoleArn: !GetAtt Roles.Outputs.RoleForChessfinderLambdaArn
        DownloadGamesQueueArn: !Ref SQS.Outputs.DownloadGamesQueueARN
        SearchBoardQueueArn: !Ref SQS.Outputs.SearchBoardQueueARN
  
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/api.yaml
      Parameters:
        ChessfinderLambdaRoleArn: !GetAtt Roles.Outputs.RoleForChessfinderLambdaArn

Outputs:
  ChessfinderApiEndpoint:
    Description: "Chessfinder API Gateway Endpoint URL"
    Value: !GetAtt Api.Outputs.ChessfinderUrl