AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Chessfinder - application for finding chessgame having only partial information about the game.

Resources:
  Roles:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/role.yaml

  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/db.yaml

  SQS:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/queue.yaml

  Async:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/async.yaml
      Parameters:
        ChessfinderLambdaRoleArn: !GetAtt Roles.Outputs.RoleForChessfinderLambdaArn
        DownloadGamesQueueArn: !GetAtt SQS.Outputs.DownloadGamesQueueArn
        SearchBoardQueueArn: !GetAtt SQS.Outputs.SearchBoardQueueArn
  
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/api.yaml
      Parameters:
        ChessfinderLambdaRoleArn: !GetAtt Roles.Outputs.RoleForChessfinderLambdaArn
  
  FasterApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: .infrastructure/faster_api.yaml
      Parameters:
        ChessfinderLambdaRoleArn: !GetAtt Roles.Outputs.RoleForChessfinderLambdaArn
        DownloadGamesQueueUrl: !GetAtt SQS.Outputs.DownloadGamesQueueUrl
        SearchBoardQueueUrl: !GetAtt SQS.Outputs.SearchBoardQueueUrl


Outputs:
  ChessfinderApiEndpoint:
    Description: "Chessfinder API Gateway Endpoint URL"
    Value: !GetAtt Api.Outputs.ChessfinderUrl
  ChessfinderFasterApiEndpoint:
    Description: "Chessfinder faster API Gateway Endpoint URL"
    Value: !GetAtt FasterApi.Outputs.ChessfinderUrl
