AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ChessfinderLambdaRoleArn:
    Type: String
Resources:
  ChessfinderFunction:
    Properties:
      Timeout: 29
      MemorySize: 1024
      Events:
        PostApiStructuredBoard:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: POST
            Path: /api/structured/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        PostApiStructuredGame:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: POST
            Path: /api/structured/game
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetApiStructuredGame:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/structured/game
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetApiStructured:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/structured
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetApiStructuredBoard:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/structured/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Runtime: java17
      CodeUri: /mnt/c/Users/tohanyan/IdeaProjects/chessfinder/chess-finder-backend/target/scala-3.3.0/chessfinder-lambda.jar
      Handler: chessfinder.api.Lambda::handleRequest
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function
  ChessfinderHttpApi:
    Properties:
      StageName: $default
    Type: AWS::Serverless::HttpApi
Outputs:
  ChessfinderUrl:
    Description: Base URL of your endpoints
    Value:
      Fn::Sub: https://${ChessfinderHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
