AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ChessfinderLambdaRoleArn:
    Type: String
Resources:
  ChessfinderFunction:
    Properties:
      Timeout: 29
      MemorySize: 1024
      Events:
        GetApiAsyncTask:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/async/task
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetApiAsyncBoard:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/async/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        PostApiAsyncGame:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: POST
            Path: /api/async/game
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        PostApiAsyncBoard:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: POST
            Path: /api/async/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetApiAsync:
          Properties:
            ApiId: !Ref 'ChessfinderHttpApi'
            Method: GET
            Path: /api/async
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Runtime: java17
      CodeUri: C:\Users\tohanyan\IdeaProjects\chessfinder\chess-finder-backend\target\scala-3.3.0\chessfinder-lambda.jar
      Handler: chessfinder.LambdaMain::handleRequest
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function
  ChessfinderHttpApi:
    Properties:
      StageName: $default
    Type: AWS::Serverless::HttpApi
Outputs:
  ChessfinderUrl:
    Description: Base URL of your endpoints
    Value:
      Fn::Sub: https://${ChessfinderHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
