AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ChessfinderLambdaRoleArn:
    Type: String
    Description: Lambda role for basic execution and permissions

  DownloadGamesQueueArn:
    Type: String
  
  SearchBoardQueueArn:
    Type: String
  
Resources:
  DownloadGamesFunction:
    Properties:
      MemorySize: 3000
      Events:
        DownloadGamesCommand:
          Properties:
            Queue: !Ref 'DownloadGamesQueueArn'
            BatchSize: 1
          Type: SQS
      Timeout: 180
      Runtime: java17
      Handler: chessfinder.download.Lambda::handleRequest
      CodeUri: ../target/scala-3.3.0/chessfinder-lambda.jar
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function

  SearchBoardFunction:
    Properties:
      MemorySize: 3000
      Events:
        SearchBoardCommand:
          Properties:
            Queue: !Ref 'SearchBoardQueueArn'
            BatchSize: 1
          Type: SQS
      Timeout: 900
      Runtime: java17
      Handler: chessfinder.search.Lambda::handleRequest
      CodeUri: ../target/scala-3.3.0/chessfinder-lambda.jar
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function
