AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DownloadGames: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "DownloadGames.fifo"
      FifoQueue: true
      VisibilityTimeout: 900

  SearchBoard: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "SearchBoard.fifo"
      FifoQueue: true
      VisibilityTimeout: 900

Outputs:
  DownloadGamesQueueURL: 
    Description: "URL of DownloadGamesQueue"
    Value: !Ref DownloadGames
  DownloadGamesQueueARN: 
    Description: "ARN of DownloadGamesQueue"
    Value: !GetAtt DownloadGames.Arn
  
  SearchBoardQueueURL: 
    Description: "URL of SearchBoardQueue"
    Value: !Ref SearchBoard
  SearchBoardQueueARN: 
    Description: "ARN of SearchBoardQueue"
    Value: !GetAtt SearchBoard.Arn