name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Check Fomatting
        shell: bash
        run: |
          sbt -v "scalafmtCheckAll;"
      - name: Compile Code
        shell: bash
        run: |
          sbt -v "compile;"
      - name: Unit Tests
        shell: bash
        run: |
          sbt -v "test;"
      - name: Integration Tests
        shell: bash
        run: |
          docker compose -f ./src/it/resources/docker-compose.yaml --env-file ./src/it/resources/.env up -d
          sleep 10s
          sbt -v "IntegrationTest / test;"
          docker compose -f ./src/it/resources/docker-compose.yaml down


