name: Deploy QA

on:
  push:
    branches: [master]

jobs:
  build:
    name: Compile, Build and Deploy QA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Compile Code
        shell: bash
        run: |
          sbt -v "compile;"
      
      - name: setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      
      - name: Packaging Code
        shell: bash
        run: |
          sbt -v "assembly; runMain chessfinder.util.SamTemplate;"
          cat template.yaml
      
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploying Application
        run: |
          sam deploy --template-file template.yaml --stack-name chessfinder --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --s3-bucket ${{ secrets.AWS_APPLICATION_BUCKET }}